services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: servisracunara
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - back-tier

  be:
    build: ./BE
    ports:
      - "8000:8000"
    volumes:
      - ./BE:/app
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: servisracunara
    depends_on:
      - db
    networks:
      - front-tier
      - back-tier

volumes:
  db-data:

networks:
  front-tier: {}
  back-tier: {}
